spring.application.name=Library

spring.datasource.url=jdbc:mysql://localhost:3306/lib_java2
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.security.username=user1
#spring.security.password=1234

spring.messages.basename=messages
spring.messages.cache-duration=0
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
